<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <PackageReference Include="BCrypt.Net-Next" Version="4.0.3" />
    <PackageReference Include="Mscc.GenerativeAI" Version="3.1.0" />
    <ProjectReference Include="..\FoodWaste.Data\FoodWaste.Data.csproj" />
    <ProjectReference Include="..\FoodWaste.Entities\FoodWaste.Entities.csproj" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

</Project>
